"""
gap_analysis_engine.py

Produces structured gap analysis findings for each applicable
privacy jurisdiction based on compliance posture answers.

Severity ratings:
  MUST_FIX     - Statutory requirement; non-compliance creates direct legal exposure
  SHOULD_FIX   - Best practice or regulatory expectation; material risk if absent
  CONSIDER     - Recommended enhancement; lower risk if absent

Each finding is a dict:
  {
    'jurisdiction':     str,  # Short name of the requirement
    'requirement':      str,   # Short name of the requirement
    'authority':        str,   # Statutory citation or regulatory reference
    'current_state':    str,  # What the client has (or doesn't have) right now
    'gap':              str,   # Description of the gap
    'policy_section':   str,  # internal_privacy_policy.docx section this cites
    'why_it_matters':   str,  # Why this requirement matters, independent of the gap itself
    'severity':         str,   # MUST_FIX | SHOULD_FIX | CONSIDER
  }

No remediation steps are included. The attorney adds those.
"""


# -----------------------------------------------
# Severity constants
# -----------------------------------------------
MUST_FIX = 'Must Fix'
SHOULD_FIX = 'Should Fix'
CONSIDER = 'Consider Fixing'


# -----------------------------------------------
# Helper
# -----------------------------------------------
def _gap(jurisdiction, requirement, authority, current_state, gap,
         policy_section, why_it_matters, severity):
    return {
        'jurisdiction': jurisdiction,
        'requirement': requirement,
        'authority': authority,
        'current_state': current_state,
        'gap': gap,
        'policy_section': policy_section,
        'why_it_matters': why_it_matters,
        'severity': severity,
    }


def _no_gap():
    """Sentinel — caller should not append this."""
    return None


# -----------------------------------------------
# GDPR Gap Analysis
# -----------------------------------------------
def analyse_gdpr_gaps(matter):
    """
    Evaluates GDPR compliance posture and returns a list
    of gap finding dicts.
    """
    findings = []
    p = matter.gdpr.posture
    g = matter.gdpr
    J = 'GDPR'

    # --- Documentation ---

    for activity in matter.processing_activities:
        if getattr(activity, 'no_lawful_basis', False):
            categories = ', '.join(activity.data_categories.true_values())
            findings.append(_gap(
                J,
                'Lawful Basis for Processing — {}'.format(activity.name),
                'Article 6 GDPR',
                'No lawful basis selected for the "{}" processing activity.'.format(
                    activity.name
                ),
                'During our documentation process, we discovered that you do '
                'not have a "lawful basis" for collecting/processing the '
                'following categories of data: {}. It is not lawful in the EU '
                'or a best practice anywhere to keep any data that you do not '
                'need to have in order to do your work. This not only '
                'protects the data subjects but also means that there is '
                'less data lost in the event of a data breach.'.format(categories),
                '1. Lawful Basis & Documentation',
                'Processing personal data without an Article 6 lawful basis '
                'is itself unlawful under GDPR, not merely undocumented — '
                'this is the foundation the rest of the compliance program '
                'rests on.',
                MUST_FIX
            ))

    # RoPA is unconditionally generated by this tool for every matter
    # (Phase 0, see BUILD_PLAN_PHASE6.md) from matters[i].processing_activities,
    # so a separate "is a RoPA maintained" attorney attestation would
    # contradict the document this engagement itself produces. Removed
    # rather than kept as a historical-practice question.

    for activity in matter.processing_activities:
        if getattr(activity, 'missing_retention_period', False):
            findings.append(_gap(
                J,
                'Data Retention Schedule — {}'.format(activity.name),
                'Article 5(1)(e) GDPR (storage limitation)',
                'No retention period documented for the "{}" processing '
                'activity.'.format(activity.name),
                'The client has not documented how long personal data is '
                'retained for the "{}" processing activity or the criteria '
                'used to determine the retention period.'.format(activity.name),
                '4. Retention',
                'Indefinite or undefined retention increases breach exposure '
                'and violates the storage limitation principle; a defined '
                'retention period is what lets old, unnecessary data '
                'actually get deleted.',
                MUST_FIX
            ))

    # LIA completion is mandatory in the interview flow wherever
    # relies_on_legitimate_interest is True (see lia_assessment.yml /
    # main.yml's required sequence), so "was an LIA done at all" is
    # never actually false by the time gap analysis runs. The
    # substantive check — did the completed LIA conclude the basis
    # doesn't survive — lives in analyse_dpia_lia_gaps below.

    # --- Notices and Consent ---

    if not p.privacy_notice_provided:
        findings.append(_gap(
            J,
            'Privacy Notice at Collection',
            'Articles 13 and 14 GDPR',
            'No privacy notice provided to data subjects at point of collection.',
            'The client does not currently provide a compliant privacy notice '
            'at or before the point of data collection as required by Articles 13/14.',
            '2. Notices & Consent',
            'Data subjects cannot exercise their rights or trust how their '
            'data is used if they were never told what is collected or why.',
            MUST_FIX
        ))

    if not p.cookie_consent_compliant:
        findings.append(_gap(
            J,
            'Cookie Consent Mechanism',
            'ePrivacy Directive; GDPR Article 6',
            'Cookie consent mechanism absent or non-compliant.',
            'The client does not have a compliant cookie consent mechanism. '
            'Non-essential cookies require prior, freely given, specific, '
            'informed, and unambiguous consent.',
            '2. Notices & Consent',
            'Non-essential cookies set without valid consent expose the '
            'client to both regulator enforcement and ePrivacy-driven '
            'complaints.',
            SHOULD_FIX
        ))

    if (g.lawful_bases.get('Consent (Article 6(1)(a))', False)
            and not p.consent_records_maintained):
        findings.append(_gap(
            J,
            'Consent Records',
            'Article 7(1) GDPR',
            'Consent relied upon but no mechanism to record or evidence consent.',
            'Where consent is the lawful basis, the controller must be able to '
            'demonstrate that the data subject has consented. No consent '
            'recording mechanism is currently in place.',
            '2. Notices & Consent',
            'Without a record of consent, the client cannot prove compliance '
            'if a data subject or regulator challenges the lawful basis '
            'relied upon.',
            MUST_FIX
        ))

    # --- Rights and Contracts ---

    if not p.rights_procedure_documented:
        findings.append(_gap(
            J,
            'Data Subject Rights Procedure',
            'Articles 15–22 GDPR',
            'No documented procedure for handling data subject rights requests.',
            'The client has no documented procedure for receiving, verifying, '
            'and responding to data subject rights requests within the one-month '
            'statutory deadline.',
            '3. Data Subject / Consumer Rights Procedures',
            "GDPR gives data subjects a one-month response deadline; without "
            "a documented intake and verification procedure, that deadline "
            "is easy to miss.",
            MUST_FIX
        ))

    if g.international_transfers and not p.transfer_mechanism_in_place:
        findings.append(_gap(
            J,
            'International Transfer Mechanism',
            'Articles 44–49 GDPR',
            'Personal data transferred outside UK/EEA without an adequate transfer mechanism.',
            'The client transfers personal data to third countries but does not '
            'have an appropriate transfer mechanism (adequacy decision, SCCs, BCRs, '
            'or IDTA) in place as required by Chapter V GDPR.',
            '1. Lawful Basis & Documentation',
            'Moving personal data outside the UK/EEA without an approved '
            'transfer mechanism is an independent violation even where the '
            'underlying processing itself is otherwise lawful.',
            MUST_FIX
        ))

    # --- Security and Breach ---
    # Breach-readiness (escalation contact, counsel on retainer) is
    # evaluated once per matter in analyse_breach_readiness_gaps below,
    # not per jurisdiction — see that function's docstring.

    # DPIA completion is mandatory in the interview flow wherever
    # activity.is_high_risk is True (see dpia_assessment.yml / main.yml's
    # required sequence), so "was a DPIA done at all" is never actually
    # false by the time gap analysis runs. The substantive check — did
    # the completed DPIA's risk register leave an unresolved high-risk
    # item — lives in analyse_dpia_lia_gaps below.

    # Staff training is evaluated once per matter in
    # analyse_staff_training_gaps below, not per jurisdiction — GDPR
    # Article 39(1)(b) and CCPA §1798.135(a)(3) are the same underlying
    # obligation in different statutory language.

    return findings


# -----------------------------------------------
# CCPA/CPRA Gap Analysis
# -----------------------------------------------
def analyse_ccpa_gaps(matter):
    """
    Evaluates CCPA/CPRA compliance posture and returns gap findings.
    """
    findings = []
    p = matter.ccpa.posture
    c = matter.ccpa
    J = 'CCPA/CPRA'

    if not p.notice_at_collection:
        findings.append(_gap(
            J,
            'Notice at Collection',
            'Cal. Civ. Code §1798.100(a)',
            'No privacy notice at collection provided to California consumers.',
            'The client does not provide a notice at or before the point of '
            'collecting personal information disclosing the categories of PI '
            'collected and the purposes for which it is used.',
            '2. Notices & Consent',
            'California consumers must be told what is collected and why '
            'before or at the point of collection — this is the CCPA analog '
            "to GDPR's Article 13/14 notice.",
            MUST_FIX
        ))

    if not p.policy_updated_12mo:
        findings.append(_gap(
            J,
            'Privacy Policy Currency',
            'Cal. Civ. Code §1798.130(a)(5)',
            'Published privacy policy not updated within the last 12 months.',
            'Businesses subject to CCPA must update their privacy policy at '
            'least once every 12 months.',
            '2. Notices & Consent',
            'A stale privacy policy misrepresents current practices and is '
            'itself a CCPA violation regardless of whether the underlying '
            'practices are compliant.',
            MUST_FIX
        ))

    if not p.policy_disclosures_complete:
        findings.append(_gap(
            J,
            'Required Privacy Policy Disclosures',
            'Cal. Civ. Code §1798.130(a)(5)',
            'Privacy policy does not include all required CCPA/CPRA disclosures.',
            'The client\'s current privacy policy is missing one or more of the '
            'disclosures required by CCPA/CPRA, including categories of PI '
            'collected, sources, purposes, third-party disclosures, and '
            'consumer rights.',
            '2. Notices & Consent',
            'Missing required disclosures (categories, sources, purposes, '
            'third-party sharing, rights) leaves consumers unable to '
            'understand or exercise their CCPA rights.',
            MUST_FIX
        ))

    if c.sells_pi and not p.opt_out_mechanism_in_place:
        findings.append(_gap(
            J,
            '"Do Not Sell or Share" Opt-Out Mechanism',
            'Cal. Civ. Code §1798.120',
            'Client sells/shares PI but no opt-out mechanism is in place.',
            'The client sells or shares personal information but has not '
            'implemented a "Do Not Sell or Share My Personal Information" '
            'link or equivalent mechanism as required.',
            '2. Notices & Consent',
            'Selling or sharing personal information without a working '
            'opt-out mechanism is a direct CCPA violation, not a '
            'best-practice gap.',
            MUST_FIX
        ))

    if not p.gpc_honoured:
        findings.append(_gap(
            J,
            'Global Privacy Control (GPC) Signal',
            'CPPA Regulations §999.315(d)',
            'Global Privacy Control signal not honoured.',
            'The client does not automatically honour the Global Privacy Control '
            'opt-out signal. This is required under CPPA regulations for businesses '
            'subject to CCPA/CPRA.',
            '2. Notices & Consent',
            'The Global Privacy Control signal is a legally recognized '
            "opt-out under CPPA regulations — ignoring it is the same as "
            "ignoring a consumer's explicit opt-out request.",
            MUST_FIX
        ))

    if c.uses_spi_beyond_primary and not p.spi_limit_mechanism_in_place:
        findings.append(_gap(
            J,
            '"Limit Use of Sensitive Personal Information" Mechanism',
            'Cal. Civ. Code §1798.121',
            'SPI used beyond primary purpose but no limit mechanism in place.',
            'The client uses sensitive personal information beyond what is '
            'necessary for the primary purpose but has not provided a mechanism '
            'for consumers to limit such use as required by §1798.121.',
            '2. Notices & Consent',
            'Consumers have an affirmative right to limit use of sensitive '
            'personal information beyond the primary purpose; without a '
            'mechanism to exercise it, that right is theoretical.',
            MUST_FIX
        ))

    if not p.rights_procedure_45_days:
        findings.append(_gap(
            J,
            'Consumer Rights Request Procedure (45-day)',
            'Cal. Civ. Code §1798.105, §1798.106',
            'No documented procedure to respond to consumer rights requests within 45 days.',
            'The client has no documented procedure for receiving and responding '
            'to consumer rights requests within the 45-day statutory deadline '
            '(extendable by an additional 45 days with notice).',
            '3. Data Subject / Consumer Rights Procedures',
            'CCPA imposes a 45-day statutory deadline (extendable once) to '
            'respond to consumer rights requests — missing it is a '
            'compliance failure regardless of the eventual substantive '
            'response.',
            MUST_FIX
        ))

    if not p.deletion_verification_in_place:
        findings.append(_gap(
            J,
            'Two-Step Verification for Deletion Requests',
            'CPPA Regulations §999.323',
            'No two-step verification process for deletion requests implemented.',
            'A two-step verification process for online deletion requests is '
            'recommended under CPPA regulations to reduce fraudulent requests.',
            '3. Data Subject / Consumer Rights Procedures',
            'Deleting data for the wrong person, or refusing a legitimate '
            'deletion request for lack of verification, are both real risks '
            'without a two-step verification process.',
            SHOULD_FIX
        ))

    return findings


# -----------------------------------------------
# TDPSA Gap Analysis
# -----------------------------------------------
def analyse_tdpsa_gaps(matter):
    """
    Evaluates TDPSA compliance posture and returns gap findings.
    """
    findings = []
    p = matter.tdpsa.posture
    t = matter.tdpsa
    J = 'TDPSA'

    if not p.privacy_notice_provided:
        findings.append(_gap(
            J,
            'Privacy Notice',
            'Tex. Bus. & Com. Code §541.101',
            'No TDPSA-compliant privacy notice provided to Texas consumers.',
            'Controllers must provide consumers with a reasonably accessible, '
            'clear, and meaningful privacy notice covering required disclosures.',
            '2. Notices & Consent',
            'Texas consumers are entitled to the same baseline notice '
            'protections as California and Virginia consumers under TDPSA.',
            MUST_FIX
        ))

    if not p.rights_procedure_45_days:
        findings.append(_gap(
            J,
            'Consumer Rights Response Procedure (45-day)',
            'Tex. Bus. & Com. Code §541.052',
            'No documented procedure to respond to consumer requests within 45 days.',
            'Controllers must respond to authenticated consumer rights requests '
            'within 45 days, with a possible 45-day extension on notice.',
            '3. Data Subject / Consumer Rights Procedures',
            'TDPSA imposes the same 45-day response structure as CCPA and '
            'VCDPA — a documented procedure is what keeps that deadline from '
            'being missed.',
            MUST_FIX
        ))

    if not p.appeals_procedure:
        findings.append(_gap(
            J,
            'Consumer Appeals Procedure',
            'Tex. Bus. & Com. Code §541.053',
            'No appeals procedure in place for denied consumer requests.',
            'Controllers must establish an internal appeals process for '
            'consumers to appeal the denial of a rights request.',
            '3. Data Subject / Consumer Rights Procedures',
            'Consumers have a statutory right to appeal a denied request; '
            'without an internal appeals process, that right cannot '
            'actually be exercised.',
            MUST_FIX
        ))

    if t.include_opt_out_section and not p.opt_out_mechanism_in_place:
        findings.append(_gap(
            J,
            'Opt-Out Mechanism for Targeted Advertising / Sale / Profiling',
            'Tex. Bus. & Com. Code §541.051',
            'No opt-out mechanism in place for applicable processing activities.',
            'The client engages in targeted advertising, sale of personal data, '
            'or profiling with significant effects but has not provided a clear '
            'mechanism for consumers to opt out.',
            '2. Notices & Consent',
            'Targeted advertising, sale, and significant-effect profiling '
            'all trigger a consumer opt-out right under TDPSA that requires '
            'an actual working mechanism.',
            MUST_FIX
        ))

    if not p.uoom_supported:
        findings.append(_gap(
            J,
            'Universal Opt-Out Mechanism (UOOM)',
            'Tex. Bus. & Com. Code §541.056',
            'Universal Opt-Out Mechanism not supported.',
            'Controllers must honour a universal opt-out mechanism recognised '
            'by the Texas Attorney General. The client does not currently '
            'support any such mechanism.',
            '2. Notices & Consent',
            'Texas requires honoring recognized universal opt-out signals — '
            'without support, individually-set opt-outs can be silently '
            'ignored at scale.',
            MUST_FIX
        ))

    if matter.footprint.processes_sensitive_data and not p.sensitive_data_consent_obtained:
        findings.append(_gap(
            J,
            'Sensitive Data Opt-In Consent',
            'Tex. Bus. & Com. Code §541.101(b)',
            'Sensitive data processed without opt-in consent mechanism.',
            'Processing of sensitive personal data requires the consumer\'s '
            'prior opt-in consent. No consent mechanism is currently in place.',
            '2. Notices & Consent',
            'Processing sensitive personal data without prior opt-in '
            'consent is a standalone TDPSA violation, independent of any '
            'other lawful basis analysis.',
            MUST_FIX
        ))

    if t.include_opt_out_section and not p.dpa_assessments_completed:
        findings.append(_gap(
            J,
            'Data Protection Assessments',
            'Tex. Bus. & Com. Code §541.105',
            'Data Protection Assessments not completed for high-risk processing.',
            'Controllers must conduct and document Data Protection Assessments '
            'before engaging in processing that presents a heightened risk of harm.',
            '9. Assessments (DPIA/LIA)',
            'Texas requires a documented risk assessment before engaging in '
            "higher-risk processing — the same underlying discipline as "
            "GDPR's DPIA, just under a different statute.",
            MUST_FIX
        ))

    return findings


# -----------------------------------------------
# VCDPA Gap Analysis
# -----------------------------------------------
def analyse_vcdpa_gaps(matter):
    """
    Evaluates VCDPA compliance posture and returns gap findings.
    """
    findings = []
    p = matter.vcdpa.posture
    v = matter.vcdpa
    J = 'VCDPA'

    if not p.privacy_notice_provided:
        findings.append(_gap(
            J,
            'Privacy Notice',
            'Va. Code Ann. §59.1-578(A)',
            'No VCDPA-compliant privacy notice provided to Virginia consumers.',
            'Controllers must provide consumers with a reasonably accessible '
            'privacy notice that includes all disclosures required by §59.1-578.',
            '2. Notices & Consent',
            'Virginia consumers are entitled to the same baseline notice '
            'protections required across every comprehensive state privacy '
            'law this tool tracks.',
            MUST_FIX
        ))

    if not p.rights_procedure_45_days:
        findings.append(_gap(
            J,
            'Consumer Rights Response Procedure (45-day)',
            'Va. Code Ann. §59.1-581(A)',
            'No documented procedure to respond to consumer requests within 45 days.',
            'Controllers must respond to authenticated consumer rights requests '
            'within 45 days. An additional 45-day extension is permitted with notice.',
            '3. Data Subject / Consumer Rights Procedures',
            "VCDPA's 45-day response deadline mirrors CCPA/TDPSA — a "
            'documented procedure is what keeps it from being missed.',
            MUST_FIX
        ))

    if not p.appeals_procedure:
        findings.append(_gap(
            J,
            'Consumer Appeals Procedure',
            'Va. Code Ann. §59.1-581(C)',
            'No appeals procedure in place for denied consumer requests.',
            'Controllers must establish and make available an internal process '
            'for consumers to appeal the denial of any rights request.',
            '3. Data Subject / Consumer Rights Procedures',
            'Virginia consumers have the same statutory appeal right as '
            'Texas consumers; without a process to handle it, the right is '
            'theoretical.',
            MUST_FIX
        ))

    if v.include_opt_out_section and not p.opt_out_mechanism_in_place:
        findings.append(_gap(
            J,
            'Opt-Out Mechanism for Targeted Advertising / Sale / Profiling',
            'Va. Code Ann. §59.1-578(A)(5)',
            'No opt-out mechanism in place for applicable processing activities.',
            'The client engages in targeted advertising, sale of personal data, '
            'or profiling with significant effects but has not provided a '
            'mechanism for consumers to opt out.',
            '2. Notices & Consent',
            'Targeted advertising, sale, and significant-effect profiling '
            'trigger a consumer opt-out right under VCDPA that requires an '
            'actual working mechanism.',
            MUST_FIX
        ))

    if v.processes_sensitive_data and not p.sensitive_data_consent_obtained:
        findings.append(_gap(
            J,
            'Sensitive Data Opt-In Consent',
            'Va. Code Ann. §59.1-578(B)',
            'Sensitive data processed without opt-in consent.',
            'Processing of sensitive data requires the consumer\'s prior, '
            'freely given, specific, and unambiguous opt-in consent. '
            'No such mechanism is currently in place.',
            '2. Notices & Consent',
            'Processing sensitive data without prior opt-in consent is a '
            'standalone VCDPA violation.',
            MUST_FIX
        ))

    if v.include_opt_out_section and not p.pia_assessments_completed:
        findings.append(_gap(
            J,
            'Data Protection Impact Assessments (PIAs)',
            'Va. Code Ann. §59.1-582',
            'Data Protection Impact Assessments not completed for high-risk processing.',
            'Controllers must conduct and document Data Protection Impact '
            'Assessments for processing activities that present a heightened '
            'risk of harm to consumers.',
            '9. Assessments (DPIA/LIA)',
            'Virginia requires a documented risk assessment before '
            "higher-risk processing — the same discipline as GDPR's DPIA "
            "and TDPSA's Data Protection Assessment.",
            MUST_FIX
        ))

    if not p.third_party_contracts_updated:
        findings.append(_gap(
            J,
            'Third-Party Contracts Updated for VCDPA',
            'Va. Code Ann. §59.1-580',
            'Contracts with third parties not reviewed or updated for VCDPA compliance.',
            'Existing contracts with third parties who receive personal data '
            'should be reviewed and updated to include VCDPA-required provisions.',
            '5. Vendor & DPA Management',
            'Older vendor contracts predating VCDPA are unlikely to include '
            'the processor obligations the statute now requires.',
            SHOULD_FIX
        ))

    return findings


# -----------------------------------------------
# Vendor DPA Gap Analysis (cross-jurisdictional)
# -----------------------------------------------
def analyse_vendor_dpa_gaps(matter):
    """
    GDPR Article 28, CCPA §1798.140(ag), TDPSA §541.104, and VCDPA
    §59.1-580 each require a DPA with processors/service providers.
    Checked once per vendor against matter.systems rather than once
    per jurisdiction against a duplicative global posture flag, so a
    vendor missing a DPA produces a single finding citing every
    applicable jurisdiction's authority instead of one near-duplicate
    finding per jurisdiction.
    """
    findings = []
    confirmed = matter.confirmed_jurisdictions.true_values()

    authorities = []
    if 'GDPR' in confirmed:
        authorities.append('Article 28 GDPR')
    if 'CCPA/CPRA' in confirmed:
        authorities.append('Cal. Civ. Code §1798.140(ag)')
    if 'TDPSA' in confirmed:
        authorities.append('Tex. Bus. & Com. Code §541.104')
    if 'VCDPA' in confirmed:
        authorities.append('Va. Code Ann. §59.1-580')

    if not authorities:
        return findings

    jurisdiction_label = ' / '.join(
        j for j in ('GDPR', 'CCPA/CPRA', 'TDPSA', 'VCDPA') if j in confirmed
    )

    for vendor in matter.systems:
        if not getattr(vendor, 'dpa_in_place', False):
            findings.append(_gap(
                jurisdiction_label,
                'Data Processing Agreement — {}'.format(vendor.name),
                '; '.join(authorities),
                'No Data Processing Agreement in place with "{}".'.format(
                    vendor.name
                ),
                'The client does not have a compliant Data Processing '
                'Agreement in place with "{}". A DPA is required wherever '
                'this vendor processes personal data on the client\'s '
                'behalf.'.format(vendor.name),
                '5. Vendor & DPA Management',
                'A missing DPA leaves the client without a binding '
                "contractual basis for a vendor's handling of personal "
                'data, and is independently required across every '
                'jurisdiction that applies to this matter.',
                MUST_FIX
            ))

    return findings


# -----------------------------------------------
# Breach Readiness Gap Analysis (cross-jurisdictional)
# -----------------------------------------------
def analyse_breach_readiness_gaps(matter):
    """
    Breach-response organizational readiness (internal escalation
    contact, counsel/forensics firm on retainer) is gathered once per
    matter in playbooks.yml regardless of which privacy-law
    jurisdictions apply — it isn't GDPR-specific even though Article
    33/34 GDPR is the only statutory citation this codebase currently
    ties to it. Runs for every matter rather than being scoped inside
    analyse_gdpr_gaps, so a US-only matter with no EU exposure still
    gets flagged for having no one designated to handle a breach.
    """
    findings = []
    pb = matter.playbooks
    gdpr_applies = 'GDPR' in matter.confirmed_jurisdictions.true_values()
    J = 'GDPR' if gdpr_applies else 'General'
    authority = (
        'Articles 33 and 34 GDPR' if gdpr_applies
        else 'General breach-response best practice'
    )

    if not pb.breach_escalation_contact:
        findings.append(_gap(
            J,
            'Data Breach Response Procedure',
            authority,
            'No internal escalation contact designated for a suspected breach.',
            'The client has not designated an internal contact responsible '
            'for detecting, assessing, and escalating a personal data '
            'breach. Without this, there is no functioning breach response '
            'procedure regardless of what documentation may say.',
            '6. Breach Response',
            'Without someone designated to receive and act on a suspected '
            'breach, statutory notification clocks can run out before '
            'anyone even starts responding.',
            MUST_FIX if gdpr_applies else SHOULD_FIX
        ))

    if not pb.breach_counsel_retained:
        findings.append(_gap(
            J,
            'Breach Counsel / Forensics Firm on Retainer',
            authority,
            'No breach counsel or forensics firm retained.',
            'The client has not retained breach counsel or a forensics firm '
            'in advance. Identifying and engaging one during an active '
            'breach costs valuable time against strict statutory '
            'notification deadlines.',
            '6. Breach Response',
            'Identifying and engaging breach counsel or a forensics firm '
            "during an active incident wastes time the client doesn't have "
            'against strict notification deadlines.',
            CONSIDER
        ))

    return findings


# -----------------------------------------------
# Security Measures Gap Analysis (cross-jurisdictional)
# -----------------------------------------------
def analyse_security_measures_gaps(matter):
    """
    Replaces the old GDPR-only Privacy by Design check with a
    per-activity check against the security_measures already gathered
    in processing_activities.yml for every activity regardless of
    jurisdiction. Cites GDPR Article 32 when GDPR applies, otherwise a
    general best-practice framing.
    """
    findings = []
    gdpr_applies = 'GDPR' in matter.confirmed_jurisdictions.true_values()
    J = 'GDPR' if gdpr_applies else 'General'
    authority = (
        'Article 32 GDPR' if gdpr_applies
        else 'General security best practice'
    )

    for activity in matter.processing_activities:
        if getattr(activity, 'no_security_measures', False):
            findings.append(_gap(
                J,
                'Security Measures — {}'.format(activity.name),
                authority,
                'No security measures selected for the "{}" processing '
                'activity.'.format(activity.name),
                'The client has not identified any technical or '
                'organizational security measures (encryption, access '
                'controls, logging, etc.) protecting the personal data '
                'processed in the "{}" activity.'.format(activity.name),
                '7. Security Program',
                'Data with no identified technical or organizational '
                'protections is the first thing a regulator or plaintiff\'s '
                'attorney will point to after an incident.',
                SHOULD_FIX
            ))

    return findings


# -----------------------------------------------
# Staff Training Gap Analysis (cross-jurisdictional)
# -----------------------------------------------
def analyse_staff_training_gaps(matter):
    """
    Consolidates GDPR Article 39(1)(b)'s staff awareness-raising/
    training obligation and CCPA/CPRA's staff-training requirement
    (§1798.135(a)(3)) into a single check against one matter-level
    flag (matters[i].playbooks.staff_trained) instead of two
    near-duplicate per-jurisdiction posture questions asking about the
    same underlying practice.
    """
    findings = []
    confirmed = matter.confirmed_jurisdictions.true_values()

    authorities = []
    if 'GDPR' in confirmed:
        authorities.append('Article 5(2) GDPR (accountability); Article 39(1)(b)')
    if 'CCPA/CPRA' in confirmed:
        authorities.append('Cal. Civ. Code §1798.135(a)(3)')

    if not authorities:
        return findings

    jurisdiction_label = ' / '.join(
        j for j in ('GDPR', 'CCPA/CPRA') if j in confirmed
    )

    if not matter.playbooks.staff_trained:
        findings.append(_gap(
            jurisdiction_label,
            'Staff Data Protection Training',
            '; '.join(authorities),
            'Staff have not received data protection training in the last '
            '12 months.',
            'No evidence of current staff training on data protection '
            'obligations, including handling of data subject/consumer '
            'rights requests. Regular training is a key element of the '
            'accountability principle and a DPO obligation where a DPO is '
            'appointed.',
            '8. Staff Training',
            'Untrained staff are the most common point of failure in an '
            'otherwise well-designed privacy program — policies and '
            'procedures only work if the people executing them know what '
            'they are.',
            SHOULD_FIX
        ))

    return findings


# -----------------------------------------------
# DPIA/LIA Substantive Gap Analysis (GDPR)
# -----------------------------------------------
def analyse_dpia_lia_gaps(matter):
    """
    DPIA/LIA completion itself is mandatory in the interview flow
    (see dpia_assessment.yml / lia_assessment.yml, both referenced in
    main.yml's required sequence), so "was it done at all" can never
    be false by the time gap analysis runs. What's actually worth
    flagging is a *completed* assessment that concluded something
    concerning: a DPIA risk register entry left at "High — processing
    should not proceed without further mitigation," or an LIA
    conclusion of "No" or "Undetermined."
    """
    findings = []
    if 'GDPR' not in matter.confirmed_jurisdictions.true_values():
        return findings

    for activity in matter.processing_activities:
        if activity.is_high_risk:
            for risk in activity.dpia.risks:
                if risk.residual_outcome == (
                    'High — processing should not proceed without '
                    'further mitigation'
                ):
                    findings.append(_gap(
                        'GDPR',
                        'Unresolved DPIA Risk — {}'.format(activity.name),
                        'Article 35 GDPR',
                        'DPIA risk register for "{}" leaves a risk at '
                        '"High — should not proceed" without further '
                        'mitigation.'.format(activity.name),
                        'The client\'s own Data Protection Impact Assessment '
                        'for the "{}" processing activity identified a risk '
                        '("{}") whose residual outcome after mitigation is '
                        'still rated High, meaning the assessment itself '
                        'concludes this processing should not proceed '
                        'without further mitigation.'.format(
                            activity.name, risk.description
                        ),
                        '9. Assessments (DPIA/LIA)',
                        "The client's own risk assessment concluded this "
                        "processing shouldn't proceed without further "
                        "mitigation — continuing without addressing it is "
                        "processing against the client's own documented "
                        "judgment.",
                        MUST_FIX
                    ))

        if activity.relies_on_legitimate_interest:
            conclusion = activity.lia.conclusion
            if conclusion == 'No — an alternative lawful basis should be used':
                findings.append(_gap(
                    'GDPR',
                    'LIA Conclusion — {}'.format(activity.name),
                    'Article 6(1)(f) GDPR',
                    'LIA for "{}" concluded the legitimate interests basis '
                    'is not supported.'.format(activity.name),
                    'The client\'s own Legitimate Interests Assessment for '
                    'the "{}" processing activity concluded that the '
                    'legitimate interests basis does not survive the '
                    'balancing test, but the activity still relies on it as '
                    'its lawful basis.'.format(activity.name),
                    '9. Assessments (DPIA/LIA)',
                    "The client's own balancing test concluded the "
                    "legitimate interests basis doesn't hold, but the "
                    'activity still relies on it — this is processing '
                    "without a valid lawful basis by the client's own "
                    'analysis.',
                    MUST_FIX
                ))
            elif conclusion == 'Undetermined — needs further review':
                findings.append(_gap(
                    'GDPR',
                    'LIA Conclusion — {}'.format(activity.name),
                    'Article 6(1)(f) GDPR',
                    'LIA for "{}" remains undetermined.'.format(activity.name),
                    'The client\'s Legitimate Interests Assessment for the '
                    '"{}" processing activity was left undetermined and '
                    'needs further review before the legitimate interests '
                    'basis can be relied upon with confidence.'.format(
                        activity.name
                    ),
                    '9. Assessments (DPIA/LIA)',
                    'An unresolved LIA leaves the activity\'s lawful basis '
                    'unconfirmed — it needs to be closed out, not left open '
                    'indefinitely.',
                    SHOULD_FIX
                ))

    return findings


# -----------------------------------------------
# Master gap analysis function (called from YAML)
# -----------------------------------------------
def run_gap_analysis(matter):
    """
    Runs all applicable gap analysis functions for the matter
    and returns a consolidated findings structure:

    {
      'all': [list of all findings],
      'by_jurisdiction': { 'GDPR': [...], 'CCPA/CPRA': [...], ... },
      'by_severity': {
          'Must Fix': [...],
          'Should Fix': [...],
          'Consider Fixing': [...]
      },
      'counts': {
          'total': int,
          'must_fix': int,
          'should_fix': int,
          'consider': int
      }
    }
    """
    confirmed = matter.confirmed_jurisdictions.true_values()
    all_findings = []

    if 'GDPR' in confirmed:
        all_findings.extend(analyse_gdpr_gaps(matter))

    if 'CCPA/CPRA' in confirmed:
        all_findings.extend(analyse_ccpa_gaps(matter))

    if 'TDPSA' in confirmed:
        all_findings.extend(analyse_tdpsa_gaps(matter))

    if 'VCDPA' in confirmed:
        all_findings.extend(analyse_vcdpa_gaps(matter))

    all_findings.extend(analyse_vendor_dpa_gaps(matter))
    all_findings.extend(analyse_breach_readiness_gaps(matter))
    all_findings.extend(analyse_security_measures_gaps(matter))
    all_findings.extend(analyse_staff_training_gaps(matter))
    all_findings.extend(analyse_dpia_lia_gaps(matter))

    by_jurisdiction = {}
    for f in all_findings:
        j = f['jurisdiction']
        by_jurisdiction.setdefault(j, []).append(f)

    by_severity = {
        MUST_FIX: [f for f in all_findings if f['severity'] == MUST_FIX],
        SHOULD_FIX: [f for f in all_findings if f['severity'] == SHOULD_FIX],
        CONSIDER: [f for f in all_findings if f['severity'] == CONSIDER],
    }

    counts = {
        'total': len(all_findings),
        'must_fix': len(by_severity[MUST_FIX]),
        'should_fix': len(by_severity[SHOULD_FIX]),
        'consider': len(by_severity[CONSIDER]),
    }

    return {
        'all': all_findings,
        'by_jurisdiction': by_jurisdiction,
        'by_severity': by_severity,
        'counts': counts,
    }
